apiVersion: v1
kind: Pod
metadata:
  name: k8s-learning
spec:
  containers:
    - name: k8s-learning
      image: k8slearning.azurecr.io/k8slearning:v2
      ports:
        - containerPort: 8080
      resources:
        requests:
          memory: "256Mi"
          cpu: "250m"
        limits:
          memory: "512Mi"
          cpu: "500m"
      livenessProbe:
        httpGet:
          path: /health
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 1
        failureThreshold: 2
      readinessProbe:
        httpGet:
          path: /readiness
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 1
        failureThreshold: 2